package com.muhammad.lumina.domain.model

import androidx.annotation.StringRes
import androidx.compose.runtime.Immutable
import com.muhammad.lumina.R

@Immutable
enum class PhotoFilter(@get:StringRes val label: Int) {
    NORMAL(label = R.string.normal),
    SEPIA(label = R.string.sepia),
    WARM(label = R.string.warn),
    COOL(label = R.string.cool),
    TEAL_ORANGE(label = R.string.teal),
    VINTAGE(label = R.string.vintage),
    MOODY(label = R.string.moody),
    BLACK_WHITE(label = R.string.black_and_white),
    CINEMATIC(R.string.cinematic),
    FADE_FILM(R.string.fade_film),
    MATTE(R.string.matte),
    VIBRANT(R.string.vibrant),
    SOFT_PASTEL(R.string.soft_pastel),
    LUSH_GREEN(R.string.lush_green),
    SUNNY_GLOW(R.string.sunny_glow),
    MONO(label = R.string.mono),
    SOFT_MONO(label = R.string.soft_mono),
    HIGH_CONTRAST_BW(label = R.string.high_contrast_bw),
    FILM_GRAIN_BW(label = R.string.film_grain_bw),
    RETRO(label = R.string.retro),
    FILTER_1977(label = R.string.filter_1977),
    OLD_PAPER(label = R.string.old_paper),
    WASHED(label = R.string.washed),
    DUOTONE_BLUE_RED(label = R.string.duotone_blue_red),
    DUOTONE_PURPLE_TEAL(label = R.string.duotone_purple_teal),
    DARK_MOODY(label = R.string.dark_moody),
    DRAMATIC(label = R.string.dramatic),
    SOFT_DREAM(label = R.string.soft_dream),
    HAZE(label = R.string.haze),
    VIGNETTE(label = R.string.vignette),
    BLOSSOM(label = R.string.blossom),
    NIGHT_BLUE(label = R.string.night_blue),
    CYBERPUNK(label = R.string.cyberpunk),
    NEON_POP(label = R.string.neon_pop ),
    GOLDEN_HOUR(label = R.string.golden_hour),
    CINNAMON(label = R.string.cinnamon),
    ROSE_GOLD(label = R.string.rose_gold),
    CARAMEL(label = R.string.caramel),
    AMBER_GLOW(label = R.string.amber_glow),
    FROST(label = R.string.frost),
    GLACIER(label = R.string.glacier),
    ARCTIC(label = R.string.arctic),
    AURORA(label = R.string.aurora),
    OCEAN_DEEP(label = R.string.ocean_deep),
    AQUA_MINT(label = R.string.aqua_mint),
    EMERALD(label = R.string.emerald),
    FOREST_FADE(label = R.string.forest_fade),
    DESERT_SAND(label = R.string.desert_sand),
    SUNSET(label = R.string.sunset),
    DREAMY_PINK(label = R.string.dreamy_pink),
    BLOOM(label = R.string.bloom),
    VELVET(label = R.string.velvet),
    NOIR_FADE(label = R.string.noir_fade)
}